# Step 1 Data Input
Thare are 5 points: (1,3), (2,5), (4,8), (7,9), (9,12)

In [1]:
import numpy as np
data = np.array([[1,3],[2,5],[4,8],[7,9],[9,12]])

# Step 2 Initialize
We could set any 2 different points in data as $c_1, c_2$. And then calculate the $W$. 

In [2]:
def dist(a, b):
    # caculate the distance between two points
    return np.sqrt(np.sum((a - b) ** 2))

def expectation(data, centers):
    # step E
    weights = np.zeros((data.shape[0], 2))
    for i, point in enumerate(data):
        d1_sq = sum((point - centers[0]) ** 2)
        d2_sq = sum((point - centers[1]) ** 2)
        weights[i, 0] = (1.0 / d1_sq) / (1.0 / d1_sq + 1.0 / d2_sq)
        weights[i, 1] = 1 - weights[i, 0]
    return weights

But here we already have $W$. Calculate the $c_1$ and $c_2$

In [3]:
def maximization(data, weights):
    # step M
    centers = np.zeros((2, 2))
    for j in range(2):
        sum_weights = np.sum(weights[:, j] ** 2)
        for i in range(data.shape[0]):
            centers[j] += weights[i, j] ** 2 * data[i]
        centers[j] /= sum_weights
    return centers

In [4]:
w1 = np.array([0.8, 0.7, 0.5, 0.3, 0.1])
w2 = 1 - w1
weights = np.vstack((w1, w2)).T

centers = maximization(data, weights)

formatted_centers = np.around(centers, decimals=4)
print(f"centers = \n {formatted_centers}")

centers = 
 [[2.2568 4.9324]
 [7.1071 9.9405]]


In [6]:
num_iterations = 3
for _ in range(num_iterations):
    weights = expectation(data, centers)
    centers = maximization(data, weights)
    print(f"Interation {_+1}:")
    formatted_weights = np.around(weights, decimals=4)
    print(f"weights = \n {formatted_weights}")
    formatted_centers = np.around(centers, decimals=4)
    print(f"centers = \n {formatted_centers}")

Interation 1:
weights = 
 [[0.9415 0.0585]
 [0.9986 0.0014]
 [0.5188 0.4812]
 [0.0224 0.9776]
 [0.0758 0.9242]]
centers = 
 [[ 1.8585  4.5724]
 [ 7.4856 10.1299]]
Interation 2:
weights = 
 [[0.9666 0.0334]
 [0.9964 0.0036]
 [0.5053 0.4947]
 [0.0318 0.9682]
 [0.0517 0.9483]]
centers = 
 [[ 1.8171  4.5061]
 [ 7.5079 10.1747]]
Interation 3:
weights = 
 [[0.9697 0.0303]
 [0.9952 0.0048]
 [0.5009 0.4991]
 [0.0336 0.9664]
 [0.0491 0.9509]]
centers = 
 [[ 1.8097  4.4937]
 [ 7.5055 10.1772]]
